plugins:
  - uses:
      - plugin: https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev
        with:
          reviewDelayTolerance: "3 Days"
          taskStaleTimeoutDuration: "30 Days"
          startRequiresWallet: true # default is true
          requiredLabelsToStart:
            - name: "Priority: 1 (Normal)"
            - name: "Priority: 2 (Medium)"
            - name: "Priority: 3 (High)"
              roles: ['collaborator', 'admin']
            - name: "Priority: 4 (Urgent)"
              roles: ['collaborator', 'admin']
            - name: "Priority: 5 (Emergency)"
              roles: ['collaborator', 'admin']
  - uses:
      - plugin: https://ubiquity-os-command-wallet-main.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquity-os-command-query-user-main.ubiquity.workers.dev
        with:
          allowPublicQuery: true
  - uses:
      - plugin: ubiquity-os-marketplace/daemon-pricing@main
        with:
          labels:
            time:
              - name: "Time: <15 Minutes"
                collaboratorOnly: false            
              - name: "Time: <1 Hour"
                collaboratorOnly: false
              - name: "Time: <2 Hours"
                collaboratorOnly: false
              - name: "Time: <4 Hours"
                collaboratorOnly: false
              - name: "Time: <1 Day"
                collaboratorOnly: false
              - name: "Time: <1 Week"
                collaboratorOnly: false
            priority:
              - name: "Priority: 1 (Normal)"
                collaboratorOnly: false
              - name: "Priority: 2 (Medium)"
                collaboratorOnly: false
              - name: "Priority: 3 (High)"
                collaboratorOnly: false
              - name: "Priority: 4 (Urgent)"
                collaboratorOnly: false
              - name: "Priority: 5 (Emergency)"
                collaboratorOnly: false
          basePriceMultiplier: 2
          publicAccessControl:
            setLabel: true
            fundExternalClosedIssue: false
  - skipBotEvents: false
    uses:
      - plugin: ubiquity-os-marketplace/text-conversation-rewards@main
        # we don't skip bot events so conversation rewards triggered by the bot also run
        with:
          evmNetworkId: 100
          evmPrivateEncrypted: "bd5AFnSCO6c5jJyPifpOfr5Zys29RE7SyXkEU3akT13RtGmYDrqGIGuvJQyH53HA5dIba7PL5bXfll0JebmwXYe5gHIXSGX80WuGMDHh0cFfeGjHhmUXe8kkZ1OT2De9qRpqejJcEzdfi-8XNAvP7cQu2Vt-7RNnPw" # https://github.com/ubiquibot/conversation-rewards/pull/111#issuecomment-2348639931
          erc20RewardToken: "0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068"
          incentives:
            contentEvaluator:
              enabled: true
            userExtractor:
              enabled: true
              redeemTask: true
            dataPurge:
              enabled: true
            formattingEvaluator:
              multipliers:
                - roles:
                    - PULL_SPECIFICATION
                  multiplier: 1
                  rewards:
                    wordValue: 0.2
                    html:
                      br:
                        score: 0
                        countWords: false
                      code:
                        score: 5
                        countWords: false
                      p:
                        score: 0
                        countWords: true
                      em:
                        score: 0
                        countWords: true
                      img:
                        score: 5
                        countWords: true
                      strong:
                        score: 0
                        countWords: false
                      blockquote:
                        score: 0
                        countWords: false
                      h1:
                        score: 1
                        countWords: true
                      h2:
                        score: 1
                        countWords: true
                      h3:
                        score: 1
                        countWords: true
                      h4:
                        score: 1
                        countWords: true
                      h5:
                        score: 1
                        countWords: true
                      h6:
                        score: 1
                        countWords: true
                      a:
                        score: 5
                        countWords: true
                      li:
                        score: 0.5
                        countWords: true
                      ul:
                        score: 1
                        countWords: true
                      td:
                        score: 0
                        countWords: true
                      hr:
                        score: 0
                        countWords: true
                      pre:
                        score: 0
                        countWords: false
                      ol:
                        score: 1
                        countWords: true
                - roles:
                    - ISSUE_SPECIFICATION
                    - ISSUE_AUTHOR
                    - ISSUE_ASSIGNEE
                    - ISSUE_COLLABORATOR
                    - ISSUE_CONTRIBUTOR
                    - PULL_ASSIGNEE
                    - PULL_COLLABORATOR
                    - PULL_CONTRIBUTOR
                  multiplier: 1
                  rewards:
                    wordValue: 0.1
                    html:
                      br:
                        score: 0
                        countWords: true
                      code:
                        score: 5
                        countWords: false
                      p:
                        score: 0
                        countWords: true
                      em:
                        score: 0
                        countWords: true
                      img:
                        score: 5
                        countWords: true
                      strong:
                        score: 0
                        countWords: false
                      blockquote:
                        score: 0
                        countWords: false
                      h1:
                        score: 1
                        countWords: true
                      h2:
                        score: 1
                        countWords: true
                      h3:
                        score: 1
                        countWords: true
                      h4:
                        score: 1
                        countWords: true
                      h5:
                        score: 1
                        countWords: true
                      h6:
                        score: 1
                        countWords: true
                      a:
                        score: 5
                        countWords: true
                      li:
                        score: 0.5
                        countWords: true
                      ul:
                        score: 1
                        countWords: true
                      td:
                        score: 0
                        countWords: true
                      hr:
                        score: 0
                        countWords: true
                      pre:
                        score: 0
                        countWords: false
                      ol:
                        score: 1
                        countWords: true
                - roles:
                    - PULL_AUTHOR
                  multiplier: 0
                  rewards:
                    wordValue: 0
            permitGeneration:
              enabled: true
            githubComment:
              post: true
              debug: false
  - uses:
      - plugin: ubiquity-os-marketplace/daemon-disqualifier@main
        with:
          watch:
            optOut:
              - ubiquibot
              - launch-party
              - staging
              - production
  - uses:
      - plugin: ubiquity-os-marketplace/daemon-merging@main
        with:
          approvalsRequired:
            collaborator: 1
          mergeTimeout:
            collaborator: "3.5 days"
          repos:
            ignore:
              - ubiquibot
              - launch-party
              - staging
              - production
  - uses:
      - plugin: ubiquity-os-marketplace/text-vector-embeddings@main
